"""Cross-backend numerical verification against CPU reference trajectories.

Reference data generated by tests/generate_reference.py on the CPU backend.

Three test tiers with decreasing strictness:
  1. Single-step: one kernel step from known state (atol=1e-6)
  2. Short-horizon: 20 steps, before chaotic divergence (atol=1e-3)
  3. Statistical: 500-step spike counts and mean voltage (10% tolerance)
"""

from __future__ import annotations

from pathlib import Path

import numpy as np
import pytest
import taichi as ti

from hypertoric.kernels.neuron_models.izhikevich import make_izhikevich_update

REFERENCE = Path(__file__).parent / "reference_trajectories.npz"

PARAMS = {
    "RS": (0.02, 0.2, -65.0, 8.0),
    "IB": (0.02, 0.2, -55.0, 4.0),
    "CH": (0.02, 0.2, -50.0, 2.0),
    "FS": (0.1, 0.2, -65.0, 2.0),
}

DT = 0.5
B, K = 1, 1
SHORT_HORIZON = 20
LONG_RUN = 500


def _alloc(v0: float, u0: float, current: float, ntype: str) -> tuple:
    a, bv, c, d = PARAMS[ntype]
    v = ti.field(dtype=ti.f32, shape=(B, K))
    u = ti.field(dtype=ti.f32, shape=(B, K))
    spikes = ti.field(dtype=ti.i32, shape=(B, K))
    i_ext = ti.field(dtype=ti.f32, shape=(B, K))
    pa = ti.field(dtype=ti.f32, shape=(B, K))
    pb = ti.field(dtype=ti.f32, shape=(B, K))
    pc = ti.field(dtype=ti.f32, shape=(B, K))
    pd = ti.field(dtype=ti.f32, shape=(B, K))
    v.from_numpy(np.full((B, K), v0, dtype=np.float32))
    u.from_numpy(np.full((B, K), u0, dtype=np.float32))
    spikes.from_numpy(np.zeros((B, K), dtype=np.int32))
    i_ext.from_numpy(np.full((B, K), current, dtype=np.float32))
    pa.from_numpy(np.full((B, K), a, dtype=np.float32))
    pb.from_numpy(np.full((B, K), bv, dtype=np.float32))
    pc.from_numpy(np.full((B, K), c, dtype=np.float32))
    pd.from_numpy(np.full((B, K), d, dtype=np.float32))
    return v, u, spikes, i_ext, pa, pb, pc, pd


SCENARIOS = [
    ("RS", 10.0),
    ("RS", 15.0),
    ("FS", 10.0),
    ("FS", 15.0),
    ("CH", 10.0),
    ("CH", 15.0),
    ("IB", 10.0),
    ("IB", 15.0),
]


@pytest.fixture(scope="module")
def ref() -> dict[str, np.ndarray]:
    """Load CPU reference trajectories."""
    if not REFERENCE.exists():
        pytest.skip(
            f"Reference file not found: {REFERENCE}\n"
            "Run: uv run python tests/generate_reference.py"
        )
    return dict(np.load(REFERENCE))


@pytest.mark.parametrize(
    "ntype,current",
    SCENARIOS,
    ids=[f"{n}_I{c:.0f}" for n, c in SCENARIOS],
)
class TestSingleStep:
    """One kernel step from known initial state — tightest tolerance."""

    def test_v_single_step(
        self, ti_cpu: None, ref: dict[str, np.ndarray], ntype: str, current: float
    ) -> None:
        key = f"{ntype}_I{current:.0f}"
        bv = PARAMS[ntype][1]
        fields = _alloc(-65.0, bv * -65.0, current, ntype)
        v, u, spikes, i_ext, pa, pb, pc, pd = fields
        kernel = make_izhikevich_update(B, K)
        kernel(v, u, spikes, i_ext, pa, pb, pc, pd, DT)
        np.testing.assert_allclose(
            v.to_numpy()[0, 0],
            ref[f"{key}_single_v"][0],
            atol=1e-6,
            rtol=1e-5,
            err_msg=f"{key}: single-step v mismatch",
        )

    def test_u_single_step(
        self, ti_cpu: None, ref: dict[str, np.ndarray], ntype: str, current: float
    ) -> None:
        key = f"{ntype}_I{current:.0f}"
        bv = PARAMS[ntype][1]
        fields = _alloc(-65.0, bv * -65.0, current, ntype)
        v, u, spikes, i_ext, pa, pb, pc, pd = fields
        kernel = make_izhikevich_update(B, K)
        kernel(v, u, spikes, i_ext, pa, pb, pc, pd, DT)
        np.testing.assert_allclose(
            u.to_numpy()[0, 0],
            ref[f"{key}_single_u"][0],
            atol=1e-6,
            rtol=1e-5,
            err_msg=f"{key}: single-step u mismatch",
        )


@pytest.mark.parametrize(
    "ntype,current",
    SCENARIOS,
    ids=[f"{n}_I{c:.0f}" for n, c in SCENARIOS],
)
class TestShortHorizon:
    """20 steps from rest — moderate tolerance before chaotic divergence."""

    def test_v_short_horizon(
        self, ti_cpu: None, ref: dict[str, np.ndarray], ntype: str, current: float
    ) -> None:
        key = f"{ntype}_I{current:.0f}"
        bv = PARAMS[ntype][1]
        fields = _alloc(-65.0, bv * -65.0, current, ntype)
        v, u, spikes, i_ext, pa, pb, pc, pd = fields
        kernel = make_izhikevich_update(B, K)
        v_trace = np.zeros(SHORT_HORIZON, dtype=np.float32)
        for step in range(SHORT_HORIZON):
            kernel(v, u, spikes, i_ext, pa, pb, pc, pd, DT)
            v_trace[step] = v.to_numpy()[0, 0]
        np.testing.assert_allclose(
            v_trace,
            ref[f"{key}_short_v"],
            atol=1e-3,
            rtol=1e-4,
            err_msg=f"{key}: short-horizon v trajectory diverged",
        )

    def test_u_short_horizon(
        self, ti_cpu: None, ref: dict[str, np.ndarray], ntype: str, current: float
    ) -> None:
        key = f"{ntype}_I{current:.0f}"
        bv = PARAMS[ntype][1]
        fields = _alloc(-65.0, bv * -65.0, current, ntype)
        v, u, spikes, i_ext, pa, pb, pc, pd = fields
        kernel = make_izhikevich_update(B, K)
        u_trace = np.zeros(SHORT_HORIZON, dtype=np.float32)
        for step in range(SHORT_HORIZON):
            kernel(v, u, spikes, i_ext, pa, pb, pc, pd, DT)
            u_trace[step] = u.to_numpy()[0, 0]
        np.testing.assert_allclose(
            u_trace,
            ref[f"{key}_short_u"],
            atol=1e-3,
            rtol=1e-4,
            err_msg=f"{key}: short-horizon u trajectory diverged",
        )


@pytest.mark.parametrize(
    "ntype,current",
    SCENARIOS,
    ids=[f"{n}_I{c:.0f}" for n, c in SCENARIOS],
)
class TestStatistical:
    """500-step aggregate statistics — loose tolerance for chaotic dynamics."""

    def test_spike_count_close(
        self, ti_cpu: None, ref: dict[str, np.ndarray], ntype: str, current: float
    ) -> None:
        """Spike count should be within ±20% of reference (or ±2 for small counts)."""
        key = f"{ntype}_I{current:.0f}"
        bv = PARAMS[ntype][1]
        fields = _alloc(-65.0, bv * -65.0, current, ntype)
        v, u, spikes, i_ext, pa, pb, pc, pd = fields
        kernel = make_izhikevich_update(B, K)
        total = 0
        for _ in range(LONG_RUN):
            kernel(v, u, spikes, i_ext, pa, pb, pc, pd, DT)
            total += int(spikes.to_numpy()[0, 0])
        ref_count = int(ref[f"{key}_spike_count"][0])
        tolerance = max(2, int(ref_count * 0.2))
        assert abs(total - ref_count) <= tolerance, (
            f"{key}: spike count {total} vs reference {ref_count} "
            f"(tolerance ±{tolerance})"
        )

    def test_mean_voltage_close(
        self, ti_cpu: None, ref: dict[str, np.ndarray], ntype: str, current: float
    ) -> None:
        """Mean voltage should be within 10% or 2 mV of reference."""
        key = f"{ntype}_I{current:.0f}"
        bv = PARAMS[ntype][1]
        fields = _alloc(-65.0, bv * -65.0, current, ntype)
        v, u, spikes, i_ext, pa, pb, pc, pd = fields
        kernel = make_izhikevich_update(B, K)
        all_v = np.zeros(LONG_RUN, dtype=np.float32)
        for step in range(LONG_RUN):
            kernel(v, u, spikes, i_ext, pa, pb, pc, pd, DT)
            all_v[step] = v.to_numpy()[0, 0]
        ref_mean = float(ref[f"{key}_mean_v"][0])
        actual_mean = float(all_v.mean())
        atol = max(2.0, abs(ref_mean) * 0.1)
        assert abs(actual_mean - ref_mean) < atol, (
            f"{key}: mean v={actual_mean:.2f} vs reference {ref_mean:.2f} "
            f"(tolerance ±{atol:.2f})"
        )
